# Generated by Django 5.2.7 on 2025-10-18 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoBaseClientesHubSoft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('id_robo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.robot')),
                ('id_tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.task')),
            ],
        ),
    ]
