# Generated by Django 5.2.7 on 2025-10-18 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atualizacaobaseclienteshubsoft',
            name='detalhes',
        ),
        migrations.AddField(
            model_name='atualizacaobaseclienteshubsoft',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Tentativas'),
        ),
        migrations.AddField(
            model_name='atualizacaobaseclienteshubsoft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atualizacaobaseclienteshubsoft',
            name='execute_after',
            field=models.DateTimeField(auto_now=True, verbose_name='Executar Após'),
        ),
        migrations.AddField(
            model_name='atualizacaobaseclienteshubsoft',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='atualizacaobaseclienteshubsoft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='atualizacaobaseclienteshubsoft',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=25, verbose_name='Status'),
        ),
    ]
