# Generated by Django 5.2.7 on 2025-10-19 01:58

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_remove_atualizacaobaseclienteshubsoft_detalhes_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='atualizacaobaseclienteshubsoft',
            trigger=pgtrigger.compiler.Trigger(name='update_task_counters', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            DECLARE\n                tarefa_uuid UUID;\n            BEGIN\n                -- Captura o ID da tarefa alterada\n                tarefa_uuid := COALESCE(NEW.id_tarefa, OLD.id_tarefa);\n\n                -- Atualiza os contadores na tabela routines_task\n                UPDATE routines_task AS t\n                SET\n                    total_rotinas = COALESCE(sub.total, 0),\n                    rotinas_pendentes = COALESCE(sub.pending, 0),\n                    rotinas_processando = COALESCE(sub.in_progress, 0),\n                    rotinas_erros = COALESCE(sub.failed, 0),\n                    rotinas_outros = COALESCE(sub.others, 0)\n                FROM (\n                    SELECT\n                        id_tarefa,\n                        COUNT(*) AS total,\n                        COUNT(*) FILTER (WHERE status = 'pending') AS pending,\n                        COUNT(*) FILTER (WHERE status = 'in_progress') AS in_progress,\n                        COUNT(*) FILTER (WHERE status = 'failed') AS failed,\n                        COUNT(*) FILTER (WHERE status NOT IN ('pending','in_progress','failed')) AS others\n                    FROM routines_atualizacaobaseclienteshubsoft\n                    GROUP BY id_tarefa\n                ) AS sub\n                WHERE t.id = tarefa_uuid\n                  AND t.id = sub.id_tarefa;\n\n                RETURN NULL;\n            END;\n        ", hash='2d41545e6fee7d879bc3b96e1623d45d985c4bf9', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_update_task_counters_9b851', table='routines_atualizacaobaseclienteshubsoft', when='AFTER')),
        ),
    ]
