# Generated by Django 5.2.7 on 2025-10-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_atualizacaobaseclienteshubsoft_update_task_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaobaseclienteshubsoft',
            name='execute_after',
            field=models.DateTimeField(default=True, verbose_name='Executar Após'),
        ),
    ]
