# Generated by Django 5.2.7 on 2025-10-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_alter_atualizacaobaseclienteshubsoft_execute_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaobaseclienteshubsoft',
            name='execute_after',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Executar Após'),
        ),
    ]
