# Generated by Django 5.2.7 on 2025-10-19 23:09

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_remove_atualizacaobaseclienteshubsoft_update_task_counters_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='atualizacaobaseclienteshubsoft',
            name='update_task_counters',
        ),
    ]
