# Generated by Django 5.2.7 on 2025-10-20 00:42

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0009_remove_atualizacaobaseclienteshubsoft_update_task_counters_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='atualizacaobaseclienteshubsoft',
            name='update_task_counters',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='atualizacaobaseclienteshubsoft',
            trigger=pgtrigger.compiler.Trigger(name='update_task_counters', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            DECLARE\n                tarefa_uuid UUID;\n            BEGIN\n                -- Captura o ID da tarefa alterada\n                tarefa_uuid := COALESCE(NEW.id_tarefa_id, OLD.id_tarefa_id);\n\n                -- Atualiza os contadores na tabela core_task\n                UPDATE core_task AS t\n                SET\n                    total_rotinas = COALESCE(sub.total, 0),\n                    rotinas_pendentes = COALESCE(sub.pending, 0),\n                    rotinas_processando = COALESCE(sub.in_progress, 0),\n                    rotinas_erros = COALESCE(sub.failed, 0),\n                    rotinas_outros = COALESCE(sub.others, 0)\n                FROM (\n                    SELECT\n                        id_tarefa_id,\n                        COUNT(*) AS total,\n                        COUNT(*) FILTER (WHERE status = 'pending') AS pending,\n                        COUNT(*) FILTER (WHERE status = 'in_progress') AS in_progress,\n                        COUNT(*) FILTER (WHERE status = 'failed') AS failed,\n                        COUNT(*) FILTER (WHERE status NOT IN ('pending','in_progress','failed')) AS others\n                    FROM routines_atualizacaobaseclienteshubsoft\n                    GROUP BY id_tarefa_id\n                ) AS sub\n                WHERE t.id = tarefa_uuid\n                  AND t.id = sub.id_tarefa_id;\n\n                RETURN NULL;\n            END;\n        ", hash='e049cf53cf14c87a24782e9a7ea955c6b0df799c', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_update_task_counters_9b851', table='routines_atualizacaobaseclienteshubsoft', when='AFTER')),
        ),
    ]
