# Generated by Django 5.2.7 on 2025-10-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0010_remove_atualizacaobaseclienteshubsoft_update_task_counters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atualizacaobaseclienteshubsoft',
            options={'verbose_name': 'Atualização Base Clientes HubSoft', 'verbose_name_plural': 'Atualizações Base Clientes HubSoft'},
        ),
    ]
