# Generated by Django 5.2.6 on 2025-10-02 19:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('roadmap', 'Roadmap'), ('in_progress', 'In Progress'), ('development', 'Development'), ('homologation', 'Homologation'), ('production', 'Production'), ('discontinued', 'Discontinued')], default='roadmap', max_length=25, verbose_name='Status')),
                ('priority', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=0, verbose_name='Prioridade')),
                ('business_day_only', models.BooleanField(default=False, verbose_name='Apenas Dias Úteis')),
                ('executor_time', models.DurationField(blank=True, null=True, verbose_name='Tempo do Executor')),
                ('average_executor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Médio do Executor')),
                ('limit_attempts', models.IntegerField(default=3, verbose_name='Limite de Tentativas')),
                ('system_restriction', models.BooleanField(default=False, verbose_name='Restrição do Sistema')),
                ('project_type', models.CharField(help_text='Informe o tipo de projeto. Ex: Python, Java', max_length=25, verbose_name='Tipo de Projeto')),
                ('git_project_url', models.CharField(help_text='Informe a URL do repositório Git.', max_length=255, verbose_name='URL do Projeto Git')),
                ('project_name', models.CharField(help_text='Informe o nome do projeto.', max_length=255, verbose_name='Nome do Projeto')),
                ('project_version', models.CharField(help_text='Informe a versão do projeto.', max_length=50, verbose_name='Versão do Projeto')),
                ('project_file_start', models.CharField(help_text='Informe o caminho do arquivo de início do projeto.', max_length=255, verbose_name='Arquivo de Início do Projeto')),
                ('table_name_schema', models.CharField(help_text='Informe o nome do schema da tabela no banco de dados.', max_length=255, verbose_name='Schema da Tabela')),
                ('table_name', models.CharField(help_text='Informe o nome da tabela no banco de dados.', max_length=255, verbose_name='Nome da Tabela')),
                ('by_pass', models.BooleanField(default=False, verbose_name='Bypass')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('restriction', models.BooleanField(default=False, verbose_name='Restrição')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('type', models.CharField(max_length=20, verbose_name='Tipo')),
                ('host_name', models.CharField(max_length=255, verbose_name='Nome do Host')),
                ('host_ip', models.GenericIPAddressField(verbose_name='IP do Host')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('error', 'Error'), ('shutting_down_systems', 'Shutting Down Systems')], default='idle', max_length=25, verbose_name='Status')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='core.automation')),
            ],
        ),
        migrations.CreateModel(
            name='RobotHasAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_robots', to='core.automation')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_automations', to='core.robot')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_of_week', models.JSONField(choices=[('mon', 'Segunda-feira'), ('tue', 'Terça-feira'), ('wed', 'Quarta-feira'), ('thu', 'Quinta-feira'), ('fri', 'Sexta-feira'), ('sat', 'Sábado'), ('sun', 'Domingo')], default=list, help_text="Selecione um ou mais dias da semana. Ex: ['mon', 'tue', 'wed']", verbose_name='Dias da Semana')),
                ('months', models.JSONField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=list, help_text='Selecione um ou mais meses. Ex: [1, 2, 3]', verbose_name='Meses')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('action', models.CharField(max_length=255, verbose_name='Ação')),
                ('business_day', models.BooleanField(default=False, verbose_name='Dia Útil')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.automation')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_restrictions', to='core.automation')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationHasSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_systems', to='core.automation')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_automations', to='core.system')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_restrictions', to='core.automation')),
            ],
        ),
    ]
