# Generated by Django 5.2.7 on 2025-10-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automation',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Automação', 'verbose_name_plural': 'Automações'},
        ),
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Robô', 'verbose_name_plural': 'Robôs'},
        ),
        migrations.AlterField(
            model_name='automation',
            name='average_executor_cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Custo Médio do Executor'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='executor_time',
            field=models.DurationField(blank=True, help_text='Tempo do executor em segundos.', null=True, verbose_name='Tempo do Executor'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='priority',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=0, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='project_type',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], help_text='Informe o tipo de projeto. Ex: Python, Java', max_length=25, verbose_name='Tipo de Projeto'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='status',
            field=models.CharField(choices=[('roadmap', 'Roadmap'), ('in_progress', 'Em Progresso'), ('development', 'Desenvolvimento'), ('homologation', 'Homologação'), ('production', 'Produção'), ('discontinued', 'Descontinuado')], default='roadmap', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='robots', to='core.automation'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.CharField(choices=[('idle', 'Ocioso'), ('working', 'Trabalhando'), ('error', 'Erro'), ('shutting_down_systems', 'Encerrando Sistemas')], default='idle', max_length=25, verbose_name='Status'),
        ),
    ]
