# Generated by Django 5.2.7 on 2025-10-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_automation_options_alter_robot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='robots', to='core.automation'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='host_ip',
            field=models.CharField(max_length=255, verbose_name='IP do Host'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='type',
            field=models.CharField(choices=[('Robot', 'Robô'), ('Developer', 'Desenvolvedor')], help_text='Informe o tipo do robô.', max_length=20, verbose_name='Tipo'),
        ),
    ]
