# Generated by Django 5.2.7 on 2025-10-05 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_robot_automation_alter_robot_host_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robothasautomation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Robô por Automação', 'verbose_name_plural': 'Robôs por Automações'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Sistema', 'verbose_name_plural': 'Sistemas'},
        ),
        migrations.AddField(
            model_name='system',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='robothasautomation',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_robots', to='core.automation', verbose_name='Automação'),
        ),
        migrations.AlterField(
            model_name='robothasautomation',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_automations', to='core.robot', verbose_name='Robô'),
        ),
        migrations.AlterUniqueTogether(
            name='robothasautomation',
            unique_together={('robot', 'automation')},
        ),
    ]
