# Generated by Django 5.2.7 on 2025-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_robothasautomation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationhassystem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sistema por Automação', 'verbose_name_plural': 'Sistemas por Automações'},
        ),
        migrations.AlterModelOptions(
            name='schedulerestriction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Restrição de Agendamento', 'verbose_name_plural': 'Restrições de Agendamento'},
        ),
        migrations.AddField(
            model_name='schedulerestriction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='schedulerestriction',
            name='end_time',
            field=models.TimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='schedulerestriction',
            name='start_time',
            field=models.TimeField(verbose_name='Início'),
        ),
        migrations.AlterUniqueTogether(
            name='automationhassystem',
            unique_together={('automation', 'system')},
        ),
    ]
