# Generated by Django 5.2.7 on 2025-10-05 19:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_automationhassystem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mon', 'Segunda-feira'), ('tue', 'Terça-feira'), ('wed', 'Quarta-feira'), ('thu', 'Quinta-feira'), ('fri', 'Sexta-feira'), ('sat', 'Sábado'), ('sun', 'Domingo')], default=list, help_text="Selecione um ou mais dias da semana. Ex: ['mon', 'tue', 'wed']", max_length=27, verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=list, help_text='Selecione um ou mais meses. Ex: [1, 2, 3]', max_length=26, verbose_name='Meses'),
        ),
    ]
