# Generated by Django 5.2.7 on 2025-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schedule_options_schedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hours',
            field=models.JSONField(default=list, help_text='Selecione um ou mais horários. Ex: [0, 12, 23]', verbose_name='Horas'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='minutes',
            field=models.JSONField(default=list, help_text='Selecione um ou mais minutos. Ex: [0, 30, 59]', verbose_name='Minutos'),
        ),
    ]
