# Generated by Django 5.2.7 on 2025-10-06 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schedule_hours_schedule_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_execution', models.DateField(verbose_name='Data de Execução')),
                ('created_task', models.BooleanField(default=False, verbose_name='Tarefa Criada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='core.automation')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Término')),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=25, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.agenda')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.automation')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='core.robot')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
    ]
