# Generated by Django 5.2.7 on 2025-10-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agenda_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
