# Generated by Django 5.2.7 on 2025-10-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date_execution',
            field=models.DateTimeField(verbose_name='Data de Execução'),
        ),
    ]
