# Generated by Django 5.2.7 on 2025-10-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_agenda_date_execution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('automation', 'date_execution')},
        ),
    ]
