# Generated by Django 5.2.7 on 2025-10-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_agenda_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('agenda',)},
        ),
    ]
