# Generated by Django 5.2.7 on 2025-10-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Prioridade da Automação'),
        ),
    ]
