# Generated by Django 5.2.7 on 2025-10-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
