# Generated by Django 5.2.7 on 2025-10-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_task_attempts_remove_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rotinas_erros',
            field=models.IntegerField(default=0, verbose_name='Rotinas com Erros'),
        ),
        migrations.AddField(
            model_name='task',
            name='rotinas_outros',
            field=models.IntegerField(default=0, verbose_name='Outros Status de Rotinas'),
        ),
        migrations.AddField(
            model_name='task',
            name='rotinas_pendentes',
            field=models.IntegerField(default=0, verbose_name='Rotinas Pendentes'),
        ),
        migrations.AddField(
            model_name='task',
            name='rotinas_processando',
            field=models.IntegerField(default=0, verbose_name='Rotinas em Processamento'),
        ),
        migrations.AddField(
            model_name='task',
            name='total_rotinas',
            field=models.IntegerField(default=0, verbose_name='Total de Rotinas'),
        ),
    ]
