# Generated by Django 5.2.7 on 2025-10-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_task_rotinas_erros_task_rotinas_outros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='robot',
        ),
    ]
