# Generated by Django 5.2.7 on 2025-10-19 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_task_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_task',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Tarefa'),
            preserve_default=False,
        ),
    ]
