# Generated by Django 5.2.7 on 2025-10-08 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(unique=True, verbose_name='ID Cliente')),
                ('uuid_cliente', models.UUIDField(editable=False, verbose_name='UUID Cliente')),
                ('codigo_cliente', models.IntegerField(verbose_name='Código Cliente')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome Cliente')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('tipo_pessoa', models.CharField(max_length=2, verbose_name='Tipo Pessoa')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('telefone_primario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Primário')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('rg_emissao', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG Emissão')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Estadual')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de Cadastro')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('origem_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem Cliente')),
                ('data_atualizacao', models.DateTimeField(verbose_name='Data de Atualização')),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil')),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo')),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente_servico', models.IntegerField(verbose_name='ID Cliente Serviço')),
                ('uuid_cliente_servico', models.UUIDField(editable=False, verbose_name='UUID Cliente Serviço')),
                ('id_servico', models.IntegerField(verbose_name='ID Serviço')),
                ('numero_plano', models.CharField(max_length=50, verbose_name='Número do Plano')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('status_prefixo', models.CharField(max_length=100, verbose_name='Status Prefixo')),
                ('tecnologia', models.CharField(max_length=100, verbose_name='Tecnologia')),
                ('velocidade_download', models.CharField(max_length=50, verbose_name='Velocidade Download')),
                ('velocidade_upload', models.CharField(max_length=50, verbose_name='Velocidade Upload')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('mac_addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC Address')),
                ('id_motivo_cancelamento', models.IntegerField(blank=True, null=True, verbose_name='ID Motivo Cancelamento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Cancelamento')),
                ('motivo_cancelamento_prefixo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Cancelamento Prefixo')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de Cadastro')),
                ('data_habilitacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Habilitação')),
                ('data_venda', models.DateTimeField(blank=True, null=True, verbose_name='Data de Venda')),
                ('data_atualizacao', models.DateTimeField(verbose_name='Data de Atualização')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawarehouse.clientes', verbose_name='Cliente')),
            ],
        ),
    ]
