# Generated by Django 5.2.7 on 2025-10-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['id_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['id_cliente', 'id_servico'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='uuid_cliente',
            field=models.UUIDField(verbose_name='UUID Cliente'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='uuid_cliente_servico',
            field=models.UUIDField(verbose_name='UUID Cliente Serviço'),
        ),
    ]
