# Generated by Django 5.2.7 on 2025-10-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouse', '0002_alter_clientes_options_alter_servicos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='data_fim_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim Contrato'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='data_inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início Contrato'),
        ),
    ]
