# Generated by Django 5.2.7 on 2025-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawarehouse', '0003_servicos_data_fim_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha'),
        ),
    ]
